### ISSUE TITLE
Help with packages in sciencedirect.py

### ISSUE THREAD

**Issue by ksarmentrout** [ScholarTools/pypub#2]
I opened sciencedirect.py and hit Run just to see the state of things right now, and the first error I've encountered is line 47, `from ..utils import get_truncated_display_string as td`. It throws the error "Attempted relative import in non-package." I've tried googling this and can't find good documentation on it. There are a few questions about it on stackoverflow, but I can't get anything to work. Thoughts?

**Comment by JimHokanson** [comment]
@ksarmentrout That file is not meant to be run directly. It could be, but I just haven't set it up as such. Generally you want to run some script which imports the package and the specific module in question. See "quick_test_code.py" for code that you can run. 

Look into documentation on importing packages and modules. See also:
http://stackoverflow.com/questions/419163/what-does-if-name-main-do
