### ISSUE TITLE
Problem with some unicode characters in references

### ISSUE THREAD

**Issue by ksarmentrout** [ScholarTools/pypub#3]
sciencedirect.py is gathering and returning things fine, but when I went to print, the `__repr__` method threw "'ascii' codec can't decode" type errors. In lines 527-534 I've been printing one attribute at a time to try and narrow down where the problem is. The first error location is in the title of reference number 34 for this example paper we're using. I just can't get it to print the whole title without problems. Thoughts?

**Comment by JimHokanson** [comment]
The problem should go away if you upgrade to Python 3. Unicode handling is one of the biggest differences between Python 2 and 3. There are workarounds but I think it is better to leave Python 2 behind. 

If you are interested, you can read more online. I'm also seen the following way of handling this ...
https://github.com/jmcarp/robobrowser/blob/4284c11d00ae1397983e269aa180e5cf7ee5f4cf/robobrowser/forms/form.py

Check out the "@encode_if_py2" decorator call ...

**Comment by ksarmentrout** [comment]
Good to know, I'll look into upgrading. Thanks!
